In [8]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import os

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas Data Frames
data1 = pd.read_csv(school_data_to_load)
data2 = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset
data_all = pd.merge(data1, data2, how="left", on=["school_name"])
data_all.head()

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
1,0,Huang High School,District,2917,1910635,1,Victor Smith,M,12th,94,61
2,0,Huang High School,District,2917,1910635,2,Kevin Rodriguez,M,12th,90,60
3,0,Huang High School,District,2917,1910635,3,Dr. Richard Scott,M,12th,67,58
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84

In [32]:
# Create a high level snapshot (in table form) of the district's key metrics, including:
# Total Schools
# Total Students
# Total Budget
# Average Math Score
#Average Reading Score
# % Passing Math
# % Passing Reading
# Overall Passing Rate (Average of the above two)
# -------------1st Try---------
# district_summary = pd.DataFrame()
# district_summary['Total Schools'] = [data1['school_name'].nunique()]
# district_summary['Total Students'] = data2['Student ID'].nunique()
# district_summary['Total Budget'] = data1['budget'].sum()
# district_summary['Average Math Score'] = round(data2['math_score'].mean(),2)
# district_summary['Average Reading Score'] = round(data2['reading_score'].mean(),2)
# district_summary['% Passing Math'] = round(data2.loc[data2['math_score'] >= 60, 'math_score'].count()/ district_summary['Total Students'] * 100,2)
# district_summary['% Passing Reading'] = round(data2.loc[data2['reading_score'] >= 60, 'reading_score'].count() / district_summary['Total Students'] * 100,2)
# district_summary['% Overall Passing Rate'] = round(np.mean([district_summary['% Passing Math'],district_summary['% Passing Reading']]),2)
# district_summary

# -------------2nd try----------
school_count = data_all['school_name'].nunique()
total_students = data_all['student_name'].count()
total_

39170

In [27]:
# Create an overview table that summarizes key metrics about each school, including:
# School Name
# School Type
# Total Students
# Total School Budget
# Per Student Budget
# Average Math Score
# Average Reading Score
# % Passing Math
# % Passing Reading
# Overall Passing Rate (Average of the above two)
grade_bins = np.array([0,59.99,100])
labels = [0,1]
data2['math_pass'] = pd.cut(data2['math_score'], bins = grade_bins, labels = labels)
data2['reading_pass'] = pd.cut(data2['reading_score'], bins = grade_bins, labels = labels)
data2['math_pass'] = pd.to_numeric(data2['math_pass'])
data2['reading_pass'] = pd.to_numeric(data2['reading_pass'])

school_type = data2.groupby(['school_name'])
total_student = data_all['Student ID'].nunique()
school_budget = data_all.set_index('school_name')['budget']
per_student_budget = school_budget / data_all.set_index('school_name')['size']
math_avg = data_all['math_score'].mean()
read_avg = data_all['reading_score'].mean()
pct_pass_math = data_all['math_pass'].sum() / total_student * 100
pct_pass_read = data_all['reading_pass'].sum() / total_student * 100
pct_pass_all = (pct_pass_math + pct_pass_read) / 2

all_school_df = pd.DataFrame({
    "School Type": school_type,
    "Total Students": total_student,
    "Total School Budget": school_budget,
    "Per Student Budget": per_student_budget,
    "Average Math Score": avg_math_score,
    "Average Reading Score": avg_reading_score,
    "% Passing Math": pct_pass_math,
    "% Passing Reading": pct_pass_read,
    "Overal Passing Rate": pct_pass_all
})

KeyError: 'math_pass'